g++ create_uclust_clusters.cpp -o create_uclust_clusters -I../lib/ffindex/src/ -L../lib/ffindex/src/ -lffindex  -Wno-write-strings
g++ -o cs adjust_cs_headers.cpp -I../lib/ffindex/src/ -L../lib/ffindex/src/ -lffindex  -Wno-write-strings
