FROM tatsushid/tinycore:6.4-x86_64

ADD mmseqs/mmseqs/bin /usr/local/mmseqs/bin
ADD mmseqs/mmseqs/lib64 /usr/local/mmseqs/lib64
ADD mmseqs/data /usr/local/mmseqs/data
ADD mmseqs/util /usr/local/mmseqs/util
ADD mmseqs/userguide.pdf /usr/local/mmseqs/userguide.pdf

ENV MMDIR /usr/local/mmseqs
ENV PATH $MMDIR/bin:$PATH

CMD ["mmseqs"]
