FROM tatsushid/tinycore:7.0-x86_64
MAINTAINER Martin Steinegger
ADD mmseqs/mmseqs/bin /usr/local/mmseqs/bin
ADD mmseqs/data /usr/local/mmseqs/data
ADD mmseqs/util /usr/local/mmseqs/util
ADD mmseqs/userguide.pdf /usr/local/mmseqs/userguide.pdf

ENV MMDIR /usr/local/mmseqs
ENV PATH $MMDIR/bin:$PATH

RUN tce-load -wic bash
RUN tce-load -wic gawk

USER tc
CMD ["mmseqs"]
