#ifndef MMSEQS_ALIGN2CLUST_CHUNKING_H
#define MMSEQS_ALIGN2CLUST_CHUNKING_H

#include <algorithm>
#include <cstddef>
#include <vector>

// Deterministic, topology-independent partitioning of the [0, endRange) index
// space used by align2clust candidate generation into fixed-size chunks.
//
// Chunk boundaries depend only on endRange and chunkSize -- never on rank
// count, thread count, or which runner launched the job -- so the same chunk
// list is produced whether a run uses 1 node or 100 nodes. This is what
// allows a run to be checkpointed under one topology and resumed under a
// different one: Align2ClustCheckpoint tracks completion per chunk index,
// and chunk indices/ranges never change when the topology changes.
namespace Align2ClustChunking {

struct Chunk {
    size_t index;
    size_t start;   // inclusive
    size_t end;     // exclusive
};

inline std::vector<Chunk> computeChunks(size_t endRange, size_t chunkSize) {
    std::vector<Chunk> chunks;
    if (endRange == 0) {
        return chunks;
    }
    chunkSize = std::max<size_t>(1, chunkSize);
    const size_t numChunks = (endRange + chunkSize - 1) / chunkSize;
    chunks.reserve(numChunks);
    for (size_t i = 0; i < numChunks; ++i) {
        Chunk chunk;
        chunk.index = i;
        chunk.start = i * chunkSize;
        chunk.end = std::min(chunk.start + chunkSize, endRange);
        chunks.push_back(chunk);
    }
    return chunks;
}

// Round-robin chunk ownership: chunk i is generated by rank (i % numProc).
// Recomputing this with a different numProc after a topology change simply
// reshuffles which rank owns which not-yet-completed chunk; already-completed
// chunks (tracked by Align2ClustCheckpoint) are never regenerated.
inline bool isChunkOwnedByRank(size_t chunkIndex, int rank, int numProc) {
    if (numProc <= 1) {
        return true;
    }
    return static_cast<int>(chunkIndex % static_cast<size_t>(numProc)) == rank;
}

}  // namespace Align2ClustChunking

#endif
